# Generated by Django 3.1.2 on 2020-10-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Tablero')),
                ('actuador', models.ManyToManyField(blank=True, to='dispositivo.Actuador', verbose_name='Actuador')),
                ('id_user_fk', models.ForeignKey(db_column='id_user_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('sensor', models.ManyToManyField(blank=True, to='dispositivo.Sensor', verbose_name='Sensor')),
            ],
            options={
                'db_table': 'tablero',
            },
        ),
        migrations.CreateModel(
            name='UserDispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dispositivo_fk', models.ForeignKey(db_column='id_dispositivo_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivo.dispositivo', verbose_name='Identificador del Controlador')),
                ('id_user_fk', models.ForeignKey(db_column='id_user_fk', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo del Usuario',
                'verbose_name_plural': 'Dispositivos del Usuario',
                'db_table': 'dispositivo_user',
                'unique_together': {('id_user_fk', 'id_dispositivo_fk')},
            },
        ),
    ]
