# Generated by Django 3.1.2 on 2020-10-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
            ],
            options={
                'db_table': 'actuador',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Controlador')),
            ],
            options={
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='TipoActuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_actuador',
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_sensor',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, verbose_name='Descripción')),
                ('id_dispositivo_fk', models.ForeignKey(db_column='id_dispositivo_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensor', to='dispositivo.dispositivo', verbose_name='Controlador')),
                ('tipo', models.ForeignKey(db_column='id_tipo_sensor_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivo.tiposensor', verbose_name='Tipo de Sensor')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='PublicacionSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_sensor_fk', models.ForeignKey(db_column='id_sensor_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivo.sensor')),
            ],
            options={
                'db_table': 'publicacion_sensor',
            },
        ),
        migrations.CreateModel(
            name='PublicacionActuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=0, max_digits=3)),
                ('id_actuador_fk', models.ForeignKey(db_column='id_actuador_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivo.actuador')),
            ],
            options={
                'db_table': 'publicacion_actuador',
            },
        ),
        migrations.AddField(
            model_name='actuador',
            name='id_dispositivo_fk',
            field=models.ForeignKey(db_column='id_dispositivo_fk', on_delete=django.db.models.deletion.DO_NOTHING, related_name='actuador', to='dispositivo.dispositivo', verbose_name='Controlador'),
        ),
        migrations.AddField(
            model_name='actuador',
            name='tipo',
            field=models.ForeignKey(db_column='id_tipo_actuador_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='dispositivo.tipoactuador', verbose_name='Tipo de Actuador'),
        ),
    ]
