# Generated by Django 3.1.2 on 2020-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0003_auto_20201017_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('evento', models.TextField()),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
